# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

platform :ios, '15.0'

install! 'cocoapods', :deterministic_uuids => false

project 'iosApp', {
  'Debug' => :debug,
  'Release' => :release,
  'Staging' => :release,
}


def shared
    pod 'shared', :path => '../shared'

end

target 'iosApp' do
    shared
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"
    end
  end
end
